name: Testing stuff

on:
  push:
    branches:
      - master
      - new-feature-z

jobs:
  a_test_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Deploy Success
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deploy Failure
        uses: rjstone/discord-webhook-notify@v1
        if: always()
        with:
          severity: error
          description: commit ${{github.event.commits[0].url}} by ${{github.event.commits[0].committer.username}} broke the build!
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
